# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build app
      inputs:
        command: build
        repository: tiredful-api
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
    
    - task: CmdLine@2
      displayName: Run container
      inputs:
        script: |        
          docker run -d --rm -p 8000:8000 --name tiredful tiredful-api

    - task: CmdLine@2
      displayName: Run functional tests
      inputs:
        script: |  
          sudo npm install -g newman      
          sudo npm install -g newman-reporter-har
          newman run TiredfulAPI.postman_collection.json         
        workingDirectory: $(System.DefaultWorkingDirectory)

    - task: CmdLine@2
      displayName: Run functional tests
      inputs:
        script: |  
          sudo dpkg -i vendor/dast-attacker-cli_1.0_amd64.deb    
          sudo dast-attacker-cli file.json                
        workingDirectory: $(System.DefaultWorkingDirectory)