# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: tiredful-api
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
    
    - task: CmdLine@2
      displayName: Run container
      inputs:
        script: |        
          docker run -d --rm -p 8000:8000 --name tiredful tiredful-api

    - task: CmdLine@2
      displayName: Install dependancies
      inputs:
        script: |        
          npm install -g newman

    - task: CmdLine@2
      displayName: Run functional tests
      inputs:
        script: |        
          newman run TiredfulAPI.postman_collection.json         