# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build app
      inputs:
        command: build
        repository: tiredful-api
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
    
    - task: CmdLine@2
      displayName: Run container
      inputs:
        script: |        
          docker run -d --rm -p 8000:8000 --name tiredful tiredful-api

    - task: CmdLine@2
      displayName: Run functional tests
      inputs:
        script: |  
          sudo npm install -g newman      
          newman run TiredfulAPI.postman_collection.json         
        workingDirectory: $(System.DefaultWorkingDirectory)

    # - task: PowerShell@2
    #   inputs:
    #     filePath: 'runproxy.ps1'

    - task: CmdLine@2
      displayName: Run security tests
      inputs:
        script: |  
          ./proxy
          export HTTP_PROXY="http://127.0.0.1:8080"
          export HTTP_PROXYS="http://127.0.0.1:8080" 
          sudo npm install -g newman-reporter-har
          wget https://github.com/whitehatsec-innovations/distribution/releases/latest/download/dast-attacker-cli.deb
          sudo dpkg -i dast-attacker-cli.deb  
          sudo dast-attacker-cli -accept-eula=Yes -license-key=2510367b-c2f2-4f83-b722-0a3ec011e5c1 -fail-on-severity=high TiredfulAPI.postman_collection.json                 
        workingDirectory: $(System.DefaultWorkingDirectory)