  trigger:
  - main

  pool:
    vmImage: 'ubuntu-1604' # set to windows-latest or another Windows vmImage for Windows builds

  variables:
    imageName: 'tiredful-demo'

  steps:
  - task: Docker@2
    displayName: Build Image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
